version: 2.1

jobs:
  create-file:
    parameters:
      file-name:
        type: string
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: create << parameters.file-name >>
          command: echo 'Text for << parameters.file-name >>' >> << parameters.file-name >>
      - persist_to_workspace:
          root: .
          paths:
            - << parameters.file-name >>

  save-as-artifacts:
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "foobar" > hoge.txt
      - run: exit 0
      - store_artifacts:
          path: /home/circleci/project

workflows:
  main:
    jobs:
      - save-as-artifacts
